---
- name: "Add users and connections to guacamole system"
  hosts: localhost
  tasks:
    - name: "Waiting for Guacamole to become healthy"
      ansible.builtin.wait_for:
        timeout: 30

    - name: "Add connections"
      scicore.guacamole.guacamole_connection:
        base_url: "{{ guacamole_url }}/guacamole"
        validate_certs: false
        auth_username: "guacadmin"
        auth_password: "guacadmin"
        connection_name: "{{ item.owner }}-{{ item.private_ip | replace('.', '-') }}"
        protocol: "rdp"
        port: 3389
        hostname: "{{ item.private_ip }}"
        username: "{{ item.user }}"
        password: "{{ item.password }}"
        rdp_ignore_server_certs: true
      loop: "{{ instances }}"
      register: connections

    - name: "Add users"
      scicore.guacamole.guacamole_user:
        base_url: "{{ guacamole_url }}/guacamole"
        validate_certs: false
        auth_username: "guacadmin"
        auth_password: "guacadmin"
        username: "{{ item }}"
        password: "changeme"
        allowed_connections: "{{ connections.results | map(attribute='connection_info.name') | select('match', item) | list }}"
        expired: "true"
      loop: "{{ users }}"
